name: flutter_cheat_repo
description: 바로 활용할 수 있는 플러터 예제 모음

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  # 데이터 모델 관리 (클래스 인스턴스 간 비교, 직관적인 String 표시 등)
  equatable: ^2.0.3

  # 상태 관리
  provider: ^6.0.3
  flutter_state_notifier: ^0.7.1
  state_notifier: ^0.7.2+1

  # 네트워킹
  ## 환경 변수의 편리한 사용
  flutter_dotenv: ^5.0.2
  ## remote API 호출
  http: ^0.13.5

  # 스타일
  ## 단어의 케이스 변경
  recase: ^4.0.0

  # 유틸리티
  ## 위젯의 unique한 Id 생성
  uuid: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
